### ISSUE TITLE
Where is Text-feature   matrix? what is json file?

### ISSUE THREAD

**Issue by myrainbowandsky** [benedekrozemberczki/TADW#3]
https://github.com/benedekrozemberczki/TADW/blob/e7ec74566368edb6e82481cc0484477fa7c35e04/src/main.py#L14

```
def read_features(feature_path):
    """
    Method to get dense node feaures.
    :param feature_path: Path to the node features.
    :return features: Node features.
    """
    features = pd.read_csv(feature_path)
    features = np.array(features)[:, 1:].transpose()
    return features
```
I think this should be the text tfidf information reduction module . Accorind to the comment it is for getting dense node features. According to  the readme, the json file is  the feature matrix. But it is the feature matrix of what? nodes feature matrix  or text feature matrix? if it is the network  information, where is the  text  feature  matrix? if it is a text feature matrix, why it  is not tf-idf of the text-data. How is the json file come? Could you show the code for producing json file?

**Comment by benedekrozemberczki** [comment]
It is a sparse binary matrix stored in a  hash map - row indices (keys), column indices values in the list. It is implemented for sparse *binary* matrices.

**Comment by myrainbowandsky** [comment]
> It is a sparse binary matrix stored in a hash map - row indices (keys), column indices values in the list. It is implemented for sparse _binary_ matrices.

thx
